/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package halaman;

import admin.dashboard;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static koneksi.konek.konek;
import koneksi.session;
import pengguna.dashboardPengguna;

/**
 *
 * @author Lenovo
 */
public class login extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        konek();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        judulLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passPasswordField = new javax.swing.JPasswordField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        belumLabel = new javax.swing.JLabel();
        daftarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(244, 248, 250));

        loginPanel.setBackground(new java.awt.Color(3, 5, 9));
        loginPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginPanel.setForeground(new java.awt.Color(3, 5, 9));

        judulLabel.setBackground(new java.awt.Color(3, 5, 9));
        judulLabel.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        judulLabel.setForeground(new java.awt.Color(244, 248, 250));
        judulLabel.setText("Login E-Lapor");

        usernameTextField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N

        passPasswordField.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N

        usernameLabel.setBackground(new java.awt.Color(3, 5, 9));
        usernameLabel.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(244, 248, 250));
        usernameLabel.setText("Username");

        passwordLabel.setBackground(new java.awt.Color(3, 5, 9));
        passwordLabel.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(244, 248, 250));
        passwordLabel.setText("Password");

        loginButton.setBackground(new java.awt.Color(244, 248, 250));
        loginButton.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(3, 5, 9));
        loginButton.setText("Login");
        loginButton.setPreferredSize(new java.awt.Dimension(63, 30));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        belumLabel.setBackground(new java.awt.Color(3, 5, 9));
        belumLabel.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        belumLabel.setForeground(new java.awt.Color(244, 248, 250));
        belumLabel.setText("Belum punya akun?");

        daftarButton.setBackground(new java.awt.Color(244, 248, 250));
        daftarButton.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        daftarButton.setForeground(new java.awt.Color(3, 5, 9));
        daftarButton.setText("Daftar");
        daftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(judulLabel)
                        .addGroup(loginPanelLayout.createSequentialGroup()
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameLabel)
                                .addComponent(passwordLabel))
                            .addGap(18, 18, 18)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(passPasswordField)))
                        .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(belumLabel)
                    .addComponent(daftarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(belumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(daftarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String user = usernameTextField.getText();
        String password = passPasswordField.getText();
        String hak = null;
        String username = null;
        
        if(user.contains(" ")){
            JOptionPane.showMessageDialog(null, "Username Tidak Boleh Ada Spasi!", "Gagal", JOptionPane.ERROR_MESSAGE);
            usernameTextField.setText("");
            passPasswordField.setText("");
            usernameTextField.requestFocus();
        }else{
            try{
            Connection con = konek();
            Statement st = con.createStatement();
            
            String sql = "SELECT * FROM akun WHERE username='" + user +"' and password='"+ password +"'";
            ResultSet rs = st.executeQuery(sql);
            
                if(rs.next()){
                    hak = rs.getString("role");
                    username = rs.getString("username");
                    JOptionPane.showMessageDialog(null, "Berhasil Login", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    session.set_Username(username);
                    if(hak.equals("pengguna")){
                        dashboardPengguna dp = new dashboardPengguna();
                        dp.setVisible(true);
                    }else if(hak.equals("admin")){
                        dashboard dash = new dashboard();
                        dash.setVisible(true);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Username atau Password Salah!", "Gagal", JOptionPane.ERROR_MESSAGE);
                    usernameTextField.setText("");
                    passPasswordField.setText("");
                    usernameTextField.requestFocus();
                }
            }catch(SQLException e){
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed
        // TODO add your handling code here:
        daftar daf = new daftar();
        daf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_daftarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel belumLabel;
    private javax.swing.JButton daftarButton;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField passPasswordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
